import hashlib
import importlib.metadata
import json
import platform
import sys
from datetime import date
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "submission_manifest.json"

FREEZE_COMMIT = "38db2af"
FREEZE_TAG = "bar-4-freeze"

# Known submission-surface files: (repo-relative path, role label).
# Frozen artifacts must always exist; generated outputs are included by
# `--update` once they exist (U3-U10 add their outputs this way).
MANIFEST_FILES = [
    ("Unihack_Full_Export_1000.csv", "frozen-export"),
    ("demo_export_50.csv", "frozen-export"),
    ("demo_input_50.csv", "frozen-export"),
    ("docs/FREEZE.md", "frozen-doc"),
    ("docs/gauntlet-progress.md", "frozen-doc"),
    ("unihack_catalog/verification_ledger.py", "frozen-tooling"),
    ("scripts/adversarial_critic.py", "frozen-eval"),
    ("scripts/adversarial_eval.py", "frozen-eval"),
    ("scripts/adversarial_holdout.csv", "frozen-eval"),
    ("scripts/adversarial_inspect.py", "frozen-eval"),
    ("scripts/adversarial_inspected.txt", "frozen-eval"),
    ("scripts/adversarial_mpns.json", "frozen-eval"),
    ("scripts/baseline_holdout.csv", "frozen-eval"),
    ("scripts/baseline_holdout_assisted.csv", "frozen-eval"),
    ("scripts/baseline_holdout_det.csv", "frozen-eval"),
    ("scripts/baseline_holdout_r1.csv", "frozen-eval"),
    ("scripts/gauntlet_holdout_eval.py", "frozen-eval"),
    ("scripts/holdout_mpns.json", "frozen-eval"),
    ("scripts/holdout_round2.csv", "frozen-eval"),
    ("scripts/rules_linter.py", "frozen-tooling"),
    ("scripts/export_rules_map.py", "frozen-tooling"),
    ("rules_map.html", "frozen-artifact"),
    ("docs/ideation/2026-08-20-submission-surface-ideation.md", "origin-doc"),
    ("scripts/check_freeze.py", "generated"),
    ("scripts/verify_manifest.py", "generated"),
    ("scripts/verify_everything.py", "generated"),
    ("scripts/build_evidence.py", "generated"),
    ("scripts/build_demo_html.py", "generated"),
    ("scripts/build_decision_log.py", "generated"),
    ("demo.html", "generated"),
    ("artifacts/metrics.json", "generated"),
    ("artifacts/evidence.json", "generated"),
    ("artifacts/decision_log.jsonl", "generated"),
    ("artifacts/acceptance_table.md", "generated"),
    ("docs/DISCLOSURE.md", "generated"),
    ("docs/RED_TEAM.md", "generated"),
    ("docs/PITCH.md", "generated"),
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    # Line-ending normalization: core.autocrlf makes working-tree vs fresh-clone
    # bytes differ (LF vs CRLF). Hash the content with \r stripped so the
    # manifest verifies identically on any checkout (R10 fresh-clone gate).
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk.replace(b"\r\n", b"\n"))
    return h.hexdigest()


def deps_versions() -> dict:
    deps = {}
    for pkg in ("pandas", "pydantic", "openai"):
        try:
            deps[pkg] = importlib.metadata.version(pkg)
        except importlib.metadata.PackageNotFoundError:
            pass
    return deps


def write_manifest() -> int:
    header = {
        "freeze_commit": FREEZE_COMMIT,
        "freeze_tag": FREEZE_TAG,
        "generated": date.today().isoformat(),
        "python": platform.python_version(),
        "deps": deps_versions(),
    }
    entries = {}
    for rel, role in MANIFEST_FILES:
        path = ROOT / rel
        if not path.is_file():
            print(f"  [SKIP] {rel} (not present yet — generated by a later unit)")
            continue
        entries[rel] = {"sha256": sha256(path), "size": path.stat().st_size, "role": role}
    manifest = {"header": header, "files": entries}
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Manifest updated: {len(entries)} files hashed -> submission_manifest.json")
    return 0


def verify() -> int:
    print("=== SUBMISSION MANIFEST VERIFY ===")
    if not MANIFEST.is_file():
        print("  [FAIL] submission_manifest.json missing — run with --update first")
        return 1
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    header = manifest.get("header", {})
    print(
        f"  freeze: {header.get('freeze_commit')} (tag {header.get('freeze_tag')}) | "
        f"generated: {header.get('generated')} | python: {header.get('python')}"
    )
    failed = 0
    entries = manifest.get("files", {})
    if not entries:
        print("  [FAIL] manifest has no file entries")
        return 1
    for rel, meta in entries.items():
        path = ROOT / rel
        if not path.is_file():
            print(f"  [FAIL] {rel} — MISSING")
            failed += 1
            continue
        actual = sha256(path)
        if actual != meta["sha256"]:
            print(f"  [FAIL] {rel} — hash mismatch (expected {meta['sha256'][:12]}… got {actual[:12]}…)")
            failed += 1
        else:
            print(f"  [PASS] {rel} ({meta.get('role', '?')})")
    print("\n" + "=" * 40)
    print(f"MANIFEST VERIFY: {'ALL PASS' if failed == 0 else f'{failed} FAILED'}")
    print("=" * 40)
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--update":
        sys.exit(write_manifest())
    sys.exit(verify())